name: Run E2E Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-e2e:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

      cognito-local:
        image: jagregory/cognito-local
        ports:
          - 9229:9229
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_REGION: us-east-1
          AWS_COGNITO_USER_POOL_ID: "local_0dB0voiS"
          AWS_COGNITO_CLIENT_ID: "6e4644fb4lqykqmxio7lme4rs"
          AWS_COGNITO_AUTHORITY: http://cognito-local:9229/
          AWS_COGNITO_ENDPOINT: http://cognito-local:9229/
        options:
          --health-cmd "curl --silent --fail http://cognito-local:9229/health | grep -q '{\"ok\":true}' || exit 1"
          --health-interval 20s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install dependencies
        run: npm install

      - name: Copy .env file
        run: |
          echo "DB_USERNAME=test" >> .env
          echo "DB_PASSWORD=test" >> .env
          echo "DB_DATABASE=test_db" >> .env
          echo "DB_PORT=5432" >> .env
          echo "PORT=3000" >> .env
          echo "AWS_COGNITO_USER_POOL_ID=local_0dB0voiS" >> .env
          echo "AWS_COGNITO_CLIENT_ID=6e4644fb4lqykqmxio7lme4rs" >> .env
          echo "AWS_COGNITO_AUTHORITY=http://cognito-local:9229/" >> .env
          echo "AWS_COGNITO_ENDPOINT=http://cognito-local:9229/" >> .env
          echo "AWS_REGION=us-east-1" >> .env
          echo "AWS_ACCESS_KEY_ID=test" >> .env
          echo "AWS_SECRET_ACCESS_KEY=test" >> .env

      - name: Wait for services to be ready
        run: sleep 10s

      - name: Run E2E tests
        run: npm run test:e2e
